Fix test flake in TestHeadTracker_New
Fixes this:

```
    mock.go:256:
        assert: mock: I don't know what to return because the method call was unexpected.
        	Either do Mock.On("Unsubscribe").Return(...) first, or remove the Unsubscribe() call.
        	This method was unexpected:
        		Unsubscribe()

        	at: [subscription.go:30 head_listener.go:207 head_listener.go:84 head_listener.go:107 asm_amd64.s:1581]
--- FAIL: TestHeadTracker_New (0.00s)
```