Add p2pv2_bootstrappers field to OCR1 job spec (#6754)
* peer_wrapper.go OCR1:  P2PV2_BOOTSTRAPPERS no longer required at startup

* services/ocr/delegate.go:  Update validation of v1 & v2 bootstrap peers

* Add p2pv2Bootstrappers field to OCR1 job spec

- Add corresponding p2pv2_bootstrappers column to ocr_oracle_specs table
- Update web / ui / presenter / resolver with new field
- Update tests

* Fix bug in develop branch which was causing several tests to fail with:

ERROR: null value in column "p2pv2_bootstrappers" of relation "ocr_oracle_specs" violates not-null constraint (SQLSTATE 23502)